# Generated by Django 6.1.1 on 2026-09-04 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic'), ('electronic', 'Electronic')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
