# Generated by Django 6.1.1 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_update_status_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollection',
            name='archived',
            field=models.BooleanField(default=False, help_text="Hidden from the admin's active list once archived, but still fully visible in the resident's own history."),
        ),
    ]
